const HOST = import.meta.env.VITE_ICP_HOST
const TOKEN_CANISTER_ID = import.meta.env.VITE_TOKEN_CANISTER_ID
const VAULT_CANISTER_ID = import.meta.env.VITE_VAULT_CANISTER_ID

console.log(HOST, TOKEN_CANISTER_ID, VAULT_CANISTER_ID)

export { HOST, TOKEN_CANISTER_ID, VAULT_CANISTER_ID };